### ISSUE TITLE
Unifier le theme entre les application GTK4, GTK3 et Flatpak

### ISSUE THREAD

**Issue by RE4V3N** [Gaming-Linux-FR/post-install-silverblue-kinoite#1]
sudo rpm-ostree install gnome-tweak-tool adw-gtk3-theme

flatpak install org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

Ouvrir "Ajustements" dans "Utilitaires" dans GNOME, onglet "Apparence", choisir Adw-gtk3 dans Anciennes applications

**Comment by Cardiacman13** [comment]
yo, merci, ça te va ? : https://github.com/Gaming-Linux-FR/post-install-silverblue-kinoite/commit/282f3791c6c62e9dc0ee190b3c8750ccee7c5512

**Comment by Cardiacman13** [comment]
ah oui merci je le précise !
