### ISSUE TITLE
Setup OpenRGB Flatpak

### ISSUE THREAD

**Issue by RE4V3N** [Gaming-Linux-FR/post-install-silverblue-kinoite#2]
sudo rpm-ostree install openrgb-udev-rules

flatpak install org.openrgb.OpenRGB

Setup d'OpenRGB avec création d'un profil qui s'appelle par exemple "fedora".

Ajouter OpenRGB au démarrage de l'ordinateur en passant par "Ajustements" dans Gnome, "Application au démarrage", appuyer sur + et choissisez OpenRGB.

Pour lancer votre profil au démarrage de l'ordinateur avec OpenRGB en minimisé :

nano ~/.config/autostart/org.openrgb.OpenRGB.desktop 

Remplacer la ligne Exec=/usr.... par :

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=openrgb org.openrgb.OpenRGB --startminimized --profile "fedora"

**Comment by Cardiacman13** [comment]
Tu me dis, si ça te vas : https://github.com/Gaming-Linux-FR/post-install-silverblue-kinoite/commit/d388f80da3483318949a5be59ce1525e99e19a7f

**Comment by RE4V3N** [comment]
Perfect 👌

**Comment by Cardiacman13** [comment]
Allez super, je ferme aussi
