### ISSUE TITLE
Installation de Steam Flatpak

### ISSUE THREAD

**Issue by RE4V3N** [Gaming-Linux-FR/post-install-silverblue-kinoite#3]
sudo rpm-ostree install steam-devices

flatpak install com.valvesoftware.Steam

Autostart minimisé :

Rajouté " -silent " entre %U et @@ dans : 

nano ~/.config/autostart/com.valvesoftware.Steam.desktop

Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam --file-forwarding com.valvesoftware.Steam @@u %U -silent @@

**Comment by Cardiacman13** [comment]
Tu me dis si ça te vas : https://github.com/Gaming-Linux-FR/post-install-silverblue-kinoite/commit/c5557acfd459d3306a7d0e8dd3e80936ff29cfb0

**Comment by RE4V3N** [comment]
Nickel, bien vu pour le second disque

**Comment by Cardiacman13** [comment]
Thx je ferme
