### ISSUE TITLE
Une petite coquille ?

### ISSUE THREAD

**Issue by DidicGLF** [Gaming-Linux-FR/post-install-silverblue-kinoite#7]
Dans la section : 

**Personnalisation de l'Apparence avec Adw-gtk3**

Il est dit que c'est uniquement utile pour SILVERBLUE, pourtant la ligne juste en dessous il est indiqué : 

> Pour personnaliser l'apparence de votre Fedora Silverblue **ou Kinoite** avec le thème Adw-gtk3, suivez ces étapes :

Le Kinoite est de trop non ?

**Comment by Cardiacman13** [comment]
Oui effectivement, il faut enlever kinoite
